site_name: 'Python App'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/daviidsantos/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  
nav:
  - Overview:
      - Getting Started: 'docs/index.md'
